apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-production"

spec:
  tls:
  - hosts:
    - kuard2.dev.greenlight.coop
    secretName: letsencrypt-production
  rules:
  - host: kuard2.dev.greenlight.coop
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard
          servicePort: 80
