apiVersion: v1
kind: Secret
metadata:
  name: admin-password-secret
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: admin-password-secret
    app.kubernetes.io/part-of: ${namespace}
type: Opaque
stringData:
  password: ${admin_password}