apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
  namespace: argocd
  labels:
    app.kubernetes.io/name: github-ssh-key
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  sshPrivateKey: |
    ${indent(4, bot_private_key)}