apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-greenlight-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: greenlight-project
  source:
    repoURL: git@github.com:greenlight-coop/argocd-greenlight-production.git
    targetRevision: ${target_revision}
    path: apps
    helm:
      values: |
        global:
          appsDomainName: ${apps_domain_name}
          knativeDomainName: ${knative_domain_name}
          useStagingCertificates: ${use_staging_certs}
          targetRevision: ${target_revision}
        value: ${target_revision}
      version: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

