apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-datasources
    app.kubernetes.io/part-of: monitoring
type: Opaque
stringData:
  grafana-datasources: |
    ${indent(4, file("manifests/grafana-datasources.yaml"))}