apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: default
  labels:
    app.kubernetes.io/name: grafana-datasources
    app.kubernetes.io/part-of: default
type: Opaque
stringData:
  datasource.yaml: |
    ${indent(4, file("manifests/grafana-datasources.yaml"))}