admin_email = "admin@greenlight.coop"
cassandra_datacenter_size = 1
cassandra_enabled = true
k8s_version = "1.22.11-do.0"
machine_type = "s-4vcpu-8gb" # https://slugs.do-api.dev/
max_node_count = 6
min_node_count = 3
region = "nyc1"
# region = "sfo3"
use_staging_certs = false