admin_email = "admin@greenlight.coop"
cassandra_enabled = true
k8s_version = "1.21.9-do.0"
machine_type = "s-4vcpu-8gb"
max_node_count = 10
min_node_count = 3
region = "nyc1"
# region = "sfo3"
use_staging_certs = false