apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-greenlight-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: greenlight-project
  source:
    repoURL: git@github.com:greenlight-coop/argocd-greenlight-infrastructure.git
    targetRevision: ${target_revision}
    path: apps
    helm:
      values: |
        global:
          apiDomainName: ${api_domain_name}
          appsDomainName: ${apps_domain_name}
          knativeDomainName: ${knative_domain_name}
          tlsCertIssuer: ${tls_cert_issuer}
          tlsSecretName: ${tls_secret_name}
          targetRevision: ${target_revision}
          isLocalKindCluster: ${is_local_kind_cluster}
          istioHttpPort: ${istio_http_port}
          istioHttpsPort: ${istio_https_port}
      version: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

