apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: greenlight-project
  source:
    repoURL: ${repo_url}
    targetRevision: ${target_revision}
    path: base/apps
    helm:
      values: |
        adminEmail: ${admin_email}
        certManager:
          enabled: ${cert_manager_enabled}
        domainName: ${domain_name}
        externalDns:
          enabled: ${external_dns_enabled}
        googleProjectId: ${google_project_id}
        metricsServer:
          enabled: ${metrics_server_enabled}
        spec:
          destination:
            server: ${destination_server}
          source:
            repoURL: ${repo_url}
            targetRevision: ${target_revision}
        useStagingCertificates: ${use_staging_certs}
  destination:
    server: ${destination_server}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

