# helm upgrade --install argocd argo/argo-cd --version 2.9.5 --namespace argocd --values helm/argocd-values.yaml --wait
# 
# In order to access the server UI you have the following options:
# 
# 1. kubectl port-forward service/argocd-server -n argocd 8080:443
# 
#     and then open the browser on http://localhost:8080 and accept the certificate
# 
# 2. enable ingress in the values file `service.ingress.enabled` and either
#       - Add the annotation for ssl passthrough: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/ingress.md#option-1-ssl-passthrough
#       - Add the `--insecure` flag to `server.extraArgs` in the values file and terminate SSL at your ingress: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/ingress.md#option-2-multiple-ingress-objects-and-hosts
# 
# After reaching the UI the first time you can login with username: admin and the password will be the
# name of the server pod. You can get the pod name by running:
# 
# kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2

installCRDs: false
server:
  ingress:
    enabled: true
    hosts:
      - argocd.dev.greenlight.coop
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   cert-manager.io/cluster-issuer: letsencrypt-production
    # tls:
    #   - secretName: letsencrypt-production
    #     hosts:
    #       - argocd.dev.greenlight.coop
    # https: true
  extraAgs:
    insecure: true
  